spring:
  datasource:
    url: jdbc:postgresql://postgres-user:5431/user-service
    username: ${USER_POSTGRES_USERNAME}
    password: ${USER_POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true


