spring:
  datasource:
    url: jdbc:postgresql://postgres:5431/user-service
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true

application:
  security:
    jwt:
      secret-key: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
